### ISSUE TITLE
2022.09.14脚手架main.js的疑问

### ISSUE THREAD

**Issue by Sagittarius-22** [Sagittarius-22/Question#2]
![微信截图_20220914180729](https://user-images.githubusercontent.com/112104249/190126181-37b30d28-0f32-405e-a30d-c093883675ab.png)
![微信截图_20220914180611](https://user-images.githubusercontent.com/112104249/190125916-dddf1944-23ab-46be-9111-2e1fd2cd67e8.png)
麻烦你看看两个src里面的main.js文件，为什么第一个可以正常解析，当把src2里面的main.js文件替换掉src1里面的，就会报错？
备注：src2里面的main.js文件是两年前创建脚手架时生成的，是我从网上教程拿到的源码文件
           src1里面的main.js文件是我今天创建脚手架时生成的

**Comment by CocaColf** [comment]
这两个用的 Vue 都不是一个大版本的吧，你现在的是 Vue3，它两年前的还是 Vue2

**Comment by Sagittarius-22** [comment]
啊，我选错了，我没仔细看创建的时候是vue3
