### ISSUE TITLE
vue练习的相关问题

### ISSUE THREAD

**Issue by Sagittarius-22** [Sagittarius-22/Question#3]
vue的视频看完了，到现在为止比计划的进度是慢了挺多的，需要抓紧对接下来的任务进行安排，我也有一些疑问，总共分为以下几点
1. 先自我评价一下，便于你了解我的情况： 我的 js 基础应该算不了多好，es6的语法不够熟练，之前那些小练习也没用到 es6，jQuery；另外已经学了一下 ajax，在学vue的时候也学了基本的向服务器发送请求和接收数据，

2. 前两天又看了一些网上前端自学的路线，感觉要学的东西还很多，因此在知识的横向扩展面上，比如 axios，node.js基础，webpack等等是不是还要继续学习，或者你认为我还有哪些是要去学习了解的；另外接下来是先学上述的基础知识，还是先做项目练习？

3.学vue时，跟着做了一个小小的练习，有点类似于之前做的 issue，但我觉得这个小练习也算不上真正的练习，然后我就去b站找了一下更加完整的项目练习视频，想跟着一起做，但是不太好找，我会继续找找看吧，
4.基于第三点，在项目练习上你有没有更好的建议或者安排？我感觉后面的练习会是一个非常重要的阶段

**Comment by Sagittarius-22** [comment]
我在github上找的案例，发现有很多是用vue写的手机移动端的案例，这类型的可以吗？还是优先做客户端的案例

**Comment by CocaColf** [comment]
1. webpack、Node.js 这些先不去管，那些东西太杂了，对于你现在没什么帮助，先把 Vue 学会和做项目
2. 项目可以在 GitHub 上找「管理系统」这种类型的项目，里面包括的内容比较多，基本一个项目做下来可以掌握很多东西
3. 项目优先做 PC 端的
